//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamDill
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int id_order { get; set; }
        public string order_number { get; set; }
        public int id_status { get; set; }
        public int id_table { get; set; }
        public int id_product { get; set; }
    
        public virtual order_status order_status { get; set; }
        public virtual products products { get; set; }
        public virtual tables tables { get; set; }
    }
}
