//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamDill
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id_user { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string mail { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string image { get; set; }
        public int id_type { get; set; }
    
        public virtual user_types user_types { get; set; }
    }
}
